module MyMimes
  MIME_TYPE_TO_FILE_EXT = { 
    'unknown/format'                  => 'unknown',
    'application/acad'                => 'dwg', # AutoCAD-Dateien (nach NCSA)
    'application/applefile'           => nil, # AppleFile-Dateien
    'application/astound'             => 'asd', # *.asn # Astound-Dateien
    'application/dsptype'             => 'tsp', # TSP-Dateien
    'application/dxf'                 => 'dxf', # AutoCAD-Dateien (nach CERN)
    'application/futuresplash'        => 'spl', # Flash Futuresplash-Dateien
    'application/gzip'                => 'gz', # GNU Zip-Dateien
    'application/listenup'            => 'ptlk', # Listenup-Dateien
    'application/mac-binhex40'        => 'hqx', # Macintosh Binärdateien
    'application/mbedlet'             => 'mbd', # Mbedlet-Dateien
    'application/mif'                 => 'mif', # FrameMaker Interchange Format Dateien
    'application/msexcel'             => 'xls', # *.xla # Microsoft Excel Dateien
    'application/mshelp'              => 'hlp', # *.chm # Microsoft Windows Hilfe Dateien
    'application/mspowerpoint'        => 'ppt', # *.ppz *.pps *.pot # Microsoft Powerpoint Dateien
    'application/msword'              => 'doc', # *.dot # Microsoft Word Dateien
    'application/octet-stream'        => 'bin', # *.exe *.com *.dll *.class # Ausführbare Dateien
    'application/oda'                 => 'oda', # Oda-Dateien
    'application/pdf'                 => 'pdf', # Adobe PDF-Dateien
    'application/postscript'          => 'ai', # *.eps *.ps # Adobe PostScript-Dateien
    'application/rtc'                 => 'rtc', # RTC-Dateien
    'application/rtf'                 => 'rtf', # Microsoft RTF-Dateien
    'application/studiom'             => 'smp', # Studiom-Dateien
    'application/toolbook'            => 'tbk', # Toolbook-Dateien
    'application/vocaltec-media-desc' => 'vmd', # Vocaltec Mediadesc-Dateien
    'application/vocaltec-media-file' => 'vmf', # Vocaltec Media-Dateien
    'application/xhtml+xml'           => 'html', # *.htm *.shtml *.xhtml # XHTML-Dateien
    'application/xml'                 => 'xml', # XML-Dateien
    'application/x-bcpio'             => 'bcpio', # BCPIO-Dateien
    'application/x-compress'          => 'z', # zlib-komprimierte Dateien
    'application/x-cpio'              => 'cpio', # CPIO-Dateien
    'application/x-csh'               => 'csh', # C-Shellscript-Dateien
    'application/x-director'          => 'dcr', # *.dir *.dxr # Macromedia Director-Dateien
    'application/x-dvi'               => 'dvi', # DVI-Dateien
    'application/x-envoy'             => 'evy', # Envoy-Dateien
    'application/x-gtar'              => 'gtar', # GNU tar-Archivdateien
    'application/x-hdf'               => 'hdf', # HDF-Dateien
    'application/x-httpd-php'         => 'php', # *.phtml # PHP-Dateien
    'application/x-javascript'        => 'js', # serverseitige JavaScript-Dateien
    'application/x-latex'             => 'latex', # LaTeX-Quelldateien
    'application/x-macbinary'         => 'bin', # Macintosh Binärdateien
    'application/x-mif'               => 'mif', # FrameMaker Interchange Format Dateien
    'application/x-netcdf'            => 'nc', # *.cdf # Unidata CDF-Dateien
    'application/x-nschat'            => 'nsc', # NS Chat-Dateien
    'application/x-sh'                => 'sh', # Bourne Shellscript-Dateien
    'application/x-shar'              => 'shar', # Shell-Archivdateien
    'application/x-shockwave-flash'   => 'swf', # *.cab # Flash Shockwave-Dateien
    'application/x-sprite'            => 'sprite', # *.spr # Sprite-Dateien
    'application/x-stuffit'           => 'sit', # Stuffit-Dateien
    'application/x-supercard'         => 'sca', # Supercard-Dateien
    'application/x-sv4cpio'           => 'sv4cpio', # CPIO-Dateien
    'application/x-sv4crc'            => 'sv4crc', # CPIO-Dateien mit CRC
    'application/x-tar'               => 'tar', # tar-Archivdateien
    'application/x-tcl'               => 'tcl', # TCL Scriptdateien
    'application/x-tex'               => 'tex', # TeX-Dateien
    'application/x-texinfo'           => 'texinfo', # *.texi # Texinfo-Dateien
    'application/x-troff'             => 't', # *.tr *.roff # TROFF-Dateien (Unix)
    'application/x-troff-man'         => 'man', # *.troff # TROFF-Dateien mit MAN-Makros (Unix)
    'application/x-troff-me'          => 'me', # *.troff # TROFF-Dateien mit ME-Makros (Unix)
    'application/x-troff-ms'          => 'me', # *.troff # TROFF-Dateien mit MS-Makros (Unix)
    'application/x-ustar'             => 'ustar', # tar-Archivdateien (Posix)
    'application/x-wais-source'       => 'src', # WAIS Quelldateien
    'application/x-www-form-urlencoded' => nil, # HTML-Formulardaten an CGI
    'application/zip'                 => 'zip', # ZIP-Archivdateien
    'audio/basic'                     => 'au', # *.snd # Sound-Dateien
    'audio/echospeech'                => 'es', # Echospeed-Dateien
    'audio/tsplayer'                  => 'tsi', # TS-Player-Dateien
    'audio/voxware'                   => 'vox', # Vox-Dateien
    'audio/x-aiff'                    => 'aiff', # *.aif *.aifc # AIFF-Sound-Dateien
    'audio/x-dspeeh'                  => 'dus', # *.cht # Sprachdateien
    'audio/x-midi'                    => 'mid', # *.midi # MIDI-Dateien
    'audio/x-mpeg'                    => 'mp2', # MPEG-Dateien
    'audio/x-pn-realaudio'            => 'ram', # *.ra # RealAudio-Dateien
    'audio/x-pn-realaudio-plugin'     => 'rpm', # RealAudio-Plugin-Dateien
    'audio/x-qt-stream'               => 'stream', # Quicktime-Streaming-Dateien
    'audio/x-wav'                     => 'wav', # WAV-Dateien
    'drawing/x-dwf'                   => 'dwf', # Drawing-Dateien
    'image/cis-cod' => 'cod', # CIS-Cod-Dateien
    'image/cmu-raster' => 'ras', # CMU-Raster-Dateien
    'image/fif' => 'fif', # FIF-Dateien
    'image/gif' => 'gif', # GIF-Dateien
    'image/ief' => 'ief', # IEF-Dateien
    'image/jpeg' => 'jpeg', # *.jpg *.jpe # JPEG-Dateien
    'image/png' => 'png', # PNG-Dateien
    'image/tiff' => 'tiff', # *.tif # TIFF-Dateien
    'image/vasa' => 'mcf', # Vasa-Dateien
    'image/vnd.wap.wbmp' => 'wbmp', # Bitmap-Dateien (WAP)
    'image/x-freehand' => 'fh4', # *.fh5 *.fhc # Freehand-Dateien
    'image/x-icon' => 'ico', # Icon-Dateien (z.B. Favoriten-Icons)
    'image/x-portable-anymap' => 'pnm', # PBM Anymap Dateien
    'image/x-portable-bitmap' => 'pbm', # PBM Bitmap Dateien
    'image/x-portable-graymap' => 'pgm', # PBM Graymap Dateien
    'image/x-portable-pixmap' => 'ppm', # PBM Pixmap Dateien
    'image/x-rgb' => 'rgb', # RGB-Dateien
    'image/x-windowdump' => 'xwd', # X-Windows Dump
    'image/x-xbitmap' => 'xbm', # XBM-Dateien
    'image/x-xpixmap' => 'xpm', # XPM-Dateien
    'message/external-body' => nil, # Nachricht mit externem Inhalt
    'message/http' => nil, # HTTP-Headernachricht
    'message/news' => nil, # Newsgroup-Nachricht
    'message/partial' => nil, # Nachricht mit Teilinhalt
    'message/rfc822' => nil, # Nachricht nach RFC 2822
    'model/vrml' => 'wrl', # Visualisierung virtueller Welten (VRML)
    'multipart/alternative' => nil, # mehrteilige Daten gemischt
    'multipart/byteranges' => nil, # mehrteilige Daten mit Byte-Angaben
    'multipart/digest' => nil, # mehrteilige Daten / Auswahl
    'multipart/encrypted' => nil, # mehrteilige Daten verschlüsselt
    'multipart/form-data' => nil, # mehrteilige Daten aus HTML-Formular (z.B. File-Upload)
    'multipart/mixed' => nil, # mehrteilige Daten gemischt
    'multipart/parallel' => nil, # mehrteilige Daten parallel
    'multipart/related' => nil, # mehrteilige Daten / verbunden
    'multipart/report' => nil, # mehrteilige Daten / Bericht
    'multipart/signed' => nil, # mehrteilige Daten / bezeichnet
    'multipart/voice-message' => nil, # mehrteilige Daten / Sprachnachricht
    'text/comma-separated-values' => 'csv', # kommaseparierte Datendateien
    'text/css' => 'css', # CSS Stylesheet-Dateien
    'text/html' => 'htm', # *.html *.shtml # HTML-Dateien
    'text/javascript' => 'js', # JavaScript-Dateien
    'text/plain' => 'txt', # reine Textdateien
    'text/richtext' => 'rtx', # Richtext-Dateien
    'text/rtf' => 'rtf', # Microsoft RTF-Dateien
    'text/tab-separated-values' => 'tsv', # tabulator-separierte Datendateien
    'text/vnd.wap.wml' => 'wml', # WML-Dateien (WAP)
    'application/vnd.wap.wmlc' => 'wmlc', # WMLC-Dateien (WAP)
    'text/vnd.wap.wmlscript' => 'wmls', # WML-Scriptdateien (WAP)
    'application/vnd.wap.wmlscriptc' => 'wmlsc', # WML-Script-C-dateien (WAP)
    'text/xml' => 'xml', # XML-Dateien
    'text/xml-external-parsed-entity' => nil, # extern geparste XML-Dateien
    'text/x-setext' => 'etx', # SeText-Dateien
    'text/x-sgml' => 'sgm', # *.sgml # SGML-Dateien
    'text/x-speech' => 'talk', # *.spc # Speech-Dateien
    'video/mpeg' => 'mpeg', # *.mpg *.mpe # MPEG-Dateien
    'video/quicktime' => 'qt', # *.mov # Quicktime-Dateien
    'video/vnd.vivo' => 'viv', # *.vivo # Vivo-Dateien
    'video/x-msvideo' => 'avi', # Microsoft AVI-Dateien
    'video/x-sgi-movie' => 'movie', # Movie-Dateien
    'workbook/formulaone' => 'vts', # *.vtts # FormulaOne-Dateien
    'x-world/x-3dmf' => '3dmf', # *.3dm *.qd3d *.qd3 # 3DMF-Dateien
    'x-world/x-vrml' => 'wrl' # Visualisierung virtueller Welten (VRML) (veralteter MIME-Typ, aktuell ist model/vrml)
  }
  
  FILE_EXT_TO_MIME_TYPE = {
    nil=>"application/octet-stream",
    '3dm' => 'x-world/x-3dmf',
    '3dmf' => 'x-world/x-3dmf',
    'ai' => 'application/postscript',
    'aif' => 'audio/x-aiff',
    'aifc' => 'audio/x-aiff',
    'aiff' => 'audio/x-aiff',
    'asd' => 'application/astound',
    'asn' => 'application/astound',
    'au' => 'audio/basic',
    'avi' => 'video/x-msvideo',
    'bcpio' => 'application/x-bcpio',
    'bin' => 'application/octet-stream',
    'cab' => 'application/x-shockwave-flash',
    'cdf' => 'application/x-netcdf',
    'chm' => 'application/mshelp',
    'cht' => 'audio/x-dspeeh',
    'class' => 'application/octet-stream',
    'cod' => 'image/cis-cod',
    'com' => 'application/octet-stream',
    'cpio' => 'application/x-cpio',
    'csh' => 'application/x-csh',
    'css' => 'text/css',
    'csv' => 'text/comma-separated-values',
    'dcr' => 'application/x-director',
    'dir' => 'application/x-director',
    'dll' => 'application/octet-stream',
    'doc' => 'application/msword',
    'dot' => 'application/msword',
    'dus' => 'audio/x-dspeeh',
    'dvi' => 'application/x-dvi',
    'dwf' => 'drawing/x-dwf',
    'dwg' => 'application/acad',
    'dxf' => 'application/dxf',
    'dxr' => 'application/x-director',
    'eps' => 'application/postscript',
    'es' => 'audio/echospeech',
    'etx' => 'text/x-setext',
    'evy' => 'application/x-envoy',
    'exe' => 'application/octet-stream',
    'fh4' => 'image/x-freehand',
    'fh5' => 'image/x-freehand',
    'fhc' => 'image/x-freehand',
    'fif' => 'image/fif',
    'gif' => 'image/gif',
    'gtar' => 'application/x-gtar',
    'gz' => 'application/gzip',
    'hdf' => 'application/x-hdf',
    'hlp' => 'application/mshelp',
    'hqx' => 'application/mac-binhex40',
    'htm' => 'text/html',
    'html' => 'text/html',
    'ico' => 'image/x-icon',
    'ief' => 'image/ief',
    'jpe' => 'image/jpeg',
    'jpeg' => 'image/jpeg',
    'jpg' => 'image/jpeg',
    'js' => 'text/javascript',
    'latex' => 'application/x-latex',
    'man' => 'application/x-troff-man',
    'mbd' => 'application/mbedlet',
    'mcf' => 'image/vasa',
    'me' => 'application/x-troff-me',
    'mid' => 'audio/x-midi',
    'midi' => 'audio/x-midi',
    'mif' => 'application/x-mif',
    'mov' => 'video/quicktime',
    'movie' => 'video/x-sgi-movie',
    'mp2' => 'audio/x-mpeg',
    'mpe' => 'video/mpeg',
    'mpeg' => 'video/mpeg',
    'mpg' => 'video/mpeg',
    'nc' => 'application/x-netcdf',
    'nsc' => 'application/x-nschat',
    'oda' => 'application/oda',
    'pbm' => 'image/x-portable-bitmap',
    'pdf' => 'application/pdf',
    'pgm' => 'image/x-portable-graymap',
    'php' => 'application/x-httpd-php',
    'phtml' => 'application/x-httpd-php',
    'png' => 'image/png',
    'pnm' => 'image/x-portable-anymap',
    'pot' => 'application/mspowerpoint',
    'ppm' => 'image/x-portable-pixmap',
    'pps' => 'application/mspowerpoint',
    'ppt' => 'application/mspowerpoint',
    'ppz' => 'application/mspowerpoint',
    'ps' => 'application/postscript',
    'ptlk' => 'application/listenup',
    'qd3' => 'x-world/x-3dmf',
    'qd3d' => 'x-world/x-3dmf',
    'qt' => 'video/quicktime',
    'ra' => 'audio/x-pn-realaudio',
    'ram' => 'audio/x-pn-realaudio',
    'ras' => 'image/cmu-raster',
    'rgb' => 'image/x-rgb',
    'roff' => 'application/x-troff',
    'rpm' => 'audio/x-pn-realaudio-plugin',
    'rtc' => 'application/rtc',
    'rtf' => 'text/rtf',
    'rtx' => 'text/richtext',
    'sca' => 'application/x-supercard',
    'sgm' => 'text/x-sgml',
    'sgml' => 'text/x-sgml',
    'sh' => 'application/x-sh',
    'shar' => 'application/x-shar',
    'shtml' => 'text/html',
    'sit' => 'application/x-stuffit',
    'smp' => 'application/studiom',
    'snd' => 'audio/basic',
    'spc' => 'text/x-speech',
    'spl' => 'application/futuresplash',
    'spr' => 'application/x-sprite',
    'sprite' => 'application/x-sprite',
    'src' => 'application/x-wais-source',
    'stream' => 'audio/x-qt-stream',
    'sv4cpio' => 'application/x-sv4cpio',
    'sv4crc' => 'application/x-sv4crc',
    'swf' => 'application/x-shockwave-flash',
    't' => 'application/x-troff',
    'talk' => 'text/x-speech',
    'tar' => 'application/x-tar',
    'tbk' => 'application/toolbook',
    'tcl' => 'application/x-tcl',
    'tex' => 'application/x-tex',
    'texi' => 'application/x-texinfo',
    'texinfo' => 'application/x-texinfo',
    'tif' => 'image/tiff',
    'tiff' => 'image/tiff',
    'tr' => 'application/x-troff',
    'troff' => 'application/x-troff-ms',
    'tsi' => 'audio/tsplayer',
    'tsp' => 'application/dsptype',
    'tsv' => 'text/tab-separated-values',
    'txt' => 'text/plain',
    'ustar' => 'application/x-ustar',
    'viv' => 'video/vnd.vivo',
    'vivo' => 'video/vnd.vivo',
    'vmd' => 'application/vocaltec-media-desc',
    'vmf' => 'application/vocaltec-media-file',
    'vox' => 'audio/voxware',
    'vts' => 'workbook/formulaone',
    'vtts' => 'workbook/formulaone',
    'wav' => 'audio/x-wav',
    'wbmp' => 'image/vnd.wap.wbmp',
    'wml' => 'text/vnd.wap.wml',
    'wmlc' => 'application/vnd.wap.wmlc',
    'wmls' => 'text/vnd.wap.wmlscript',
    'wmlsc' => 'application/vnd.wap.wmlscriptc',
    'wrl' => 'model/vrml',
    'xbm' => 'image/x-xbitmap',
    'xhtml' => 'application/xhtml+xml',
    'xla' => 'application/msexcel',
    'xls' => 'application/msexcel',
    'xml' => 'text/xml',
    'xpm' => 'image/x-xpixmap',
    'xwd' => 'image/x-windowdump',
    'z' => 'application/x-compress',
    'zip' => 'application/zip'
  }

  THUMBNAIL_ABLES = [
    #'image/fif',  # FIF-Dateien
    'image/gif',  # GIF-Dateien
    #'image/ief',  # IEF-Dateien
    'image/jpeg',  # *.jpg *.jpe # JPEG-Dateien
    'image/png',  # PNG-Dateien
    'image/tiff',  # *.tif # TIFF-Dateien
    #'image/vasa',  # Vasa-Dateien
    #'image/vnd.wap.wbmp',  # Bitmap-Dateien (WAP)
    #'image/x-freehand',  # *.fh5 *.fhc # Freehand-Dateien
    'image/x-icon',  # Icon-Dateien (z.B. Favoriten-Icons)
    #'image/x-portable-anymap',  # PBM Anymap Dateien
    #'image/x-portable-bitmap',  # PBM Bitmap Dateien
    #'image/x-portable-graymap',  # PBM Graymap Dateien
    #'image/x-portable-pixmap',  # PBM Pixmap Dateien
    #'image/x-rgb',  # RGB-Dateien
    #'image/x-windowdump',  # X-Windows Dump
    'image/x-xbitmap',  # XBM-Dateien
    'image/x-xpixmap' # XPM-Dateien
  ]
  
  FILE_EXT_TO_MIME_TYPE_ALT = { 
    nil => 'unknown/format',
    'dwg' => 'application/acad',
    'asd' => 'application/astound',
    'asn' => 'application/astound',
    'tsp' => 'application/dsptype',
    'dxf' => 'application/dxf',
    'spl' => 'application/futuresplash',
    'gz' => 'application/gzip',
    'ptlk' => 'application/listenup',
    'hqx' => 'application/mac-binhex40',
    'mbd' => 'application/mbedlet',
    'mif' => 'application/mif',
    'xls' => 'application/msexcel',
    'xla' => 'application/msexcel',
    'hlp' => 'application/mshelp',
    'chm' => 'application/mshelp',
    'ppt' => 'application/mspowerpoint',
    'ppz' => 'application/mspowerpoint',
    'pps' => 'application/mspowerpoint',
    'pot' => 'application/mspowerpoint',
    'doc' => 'application/msword',
    'dot' => 'application/msword',
    'bin' => 'application/octet-stream',
    'exe' => 'application/octet-stream',
    'com' => 'application/octet-stream',
    'dll' => 'application/octet-stream',
    'class' => 'application/octet-stream',
    'oda' => 'application/oda',
    'pdf' => 'application/pdf',
    'ai' => 'application/postscript',
    'eps' => 'application/postscript',
    'ps' => 'application/postscript',
    'rtc' => 'application/rtc',
    'rtf' => 'application/rtf',
    'smp' => 'application/studiom',
    'tbk' => 'application/toolbook',
    'vmd' => 'application/vocaltec-media-desc',
    'vmf' => 'application/vocaltec-media-file',
    'html' => 'application/xhtml+xml',
    'htm' => 'application/xhtml+xml',
    'shtml' => 'application/xhtml+xml',
    'xhtml' => 'application/xhtml+xml',
    'xml' => 'application/xml',
    'bcpio' => 'application/x-bcpio',
    'z' => 'application/x-compress',
    'cpio' => 'application/x-cpio',
    'csh' => 'application/x-csh',
    'dcr' => 'application/x-director',
    'dir' => 'application/x-director',
    'dxr' => 'application/x-director',
    'dvi' => 'application/x-dvi',
    'evy' => 'application/x-envoy',
    'gtar' => 'application/x-gtar',
    'hdf' => 'application/x-hdf',
    'php' => 'application/x-httpd-php',
    'phtml' => 'application/x-httpd-php',
    'js' => 'application/x-javascript',
    'latex' => 'application/x-latex',
    'bin' => 'application/x-macbinary',
    'mif' => 'application/x-mif',
    'nc' => 'application/x-netcdf',
    'cdf' => 'application/x-netcdf',
    'nsc' => 'application/x-nschat',
    'sh' => 'application/x-sh',
    'shar' => 'application/x-shar',
    'swf' => 'application/x-shockwave-flash',
    'cab' => 'application/x-shockwave-flash',
    'sprite' => 'application/x-sprite',
    'spr' => 'application/x-sprite',
    'sit' => 'application/x-stuffit',
    'sca' => 'application/x-supercard',
    'sv4cpio' => 'application/x-sv4cpio',
    'sv4crc' => 'application/x-sv4crc',
    'tar' => 'application/x-tar',
    'tcl' => 'application/x-tcl',
    'tex' => 'application/x-tex',
    'texinfo' => 'application/x-texinfo',
    'texi' => 'application/x-texinfo',
    't' => 'application/x-troff',
    'tr' => 'application/x-troff',
    'roff' => 'application/x-troff',
    'man' => 'application/x-troff-man',
    'troff' => 'application/x-troff-man',
    'me' => 'application/x-troff-me',
    'troff' => 'application/x-troff-me',
    'me' => 'application/x-troff-ms',
    'troff' => 'application/x-troff-ms',
    'ustar' => 'application/x-ustar',
    'src' => 'application/x-wais-source',
    'zip' => 'application/zip',
    'au' => 'audio/basic',
    'snd' => 'audio/basic',
    'es' => 'audio/echospeech',
    'tsi' => 'audio/tsplayer',
    'vox' => 'audio/voxware',
    'aiff' => 'audio/x-aiff',
    'aif' => 'audio/x-aiff',
    'aifc' => 'audio/x-aiff',
    'dus' => 'audio/x-dspeeh',
    'cht' => 'audio/x-dspeeh',
    'mid' => 'audio/x-midi',
    'midi' => 'audio/x-midi',
    'mp2' => 'audio/x-mpeg',
    'ram' => 'audio/x-pn-realaudio',
    'ra' => 'audio/x-pn-realaudio',
    'rpm' => 'audio/x-pn-realaudio-plugin',
    'stream' => 'audio/x-qt-stream',
    'wav' => 'audio/x-wav',
    'dwf' => 'drawing/x-dwf',
    'cod' => 'image/cis-cod',
    'ras' => 'image/cmu-raster',
    'fif' => 'image/fif',
    'gif' => 'image/gif',
    'ief' => 'image/ief',
    'jpeg' => 'image/jpeg',
    'jpg' => 'image/jpeg',
    'jpe' => 'image/jpeg',
    'png' => 'image/png',
    'tiff' => 'image/tiff',
    'tif' => 'image/tiff',
    'mcf' => 'image/vasa',
    'wbmp' => 'image/vnd.wap.wbmp',
    'fh4' => 'image/x-freehand',
    'fh5' => 'image/x-freehand',
    'fhc' => 'image/x-freehand',
    'ico' => 'image/x-icon',
    'pnm' => 'image/x-portable-anymap',
    'pbm' => 'image/x-portable-bitmap',
    'pgm' => 'image/x-portable-graymap',
    'ppm' => 'image/x-portable-pixmap',
    'rgb' => 'image/x-rgb',
    'xwd' => 'image/x-windowdump',
    'xbm' => 'image/x-xbitmap',
    'xpm' => 'image/x-xpixmap',
    'wrl' => 'model/vrml',
    'csv' => 'text/comma-separated-values',
    'css' => 'text/css',
    'htm' => 'text/html',
    'html' => 'text/html',
    'shtml' => 'text/html',
    'js' => 'text/javascript',
    'txt' => 'text/plain',
    'rtx' => 'text/richtext',
    'rtf' => 'text/rtf',
    'tsv' => 'text/tab-separated-values',
    'wml' => 'text/vnd.wap.wml',
    'wmlc' => 'application/vnd.wap.wmlc',
    'wmls' => 'text/vnd.wap.wmlscript',
    'wmlsc' => 'application/vnd.wap.wmlscriptc',
    'xml' => 'text/xml',
    'etx' => 'text/x-setext',
    'sgm' => 'text/x-sgml',
    'sgml' => 'text/x-sgml',
    'talk' => 'text/x-speech',
    'spc' => 'text/x-speech',
    'mpeg' => 'video/mpeg',
    'mpg' => 'video/mpeg',
    'mpe' => 'video/mpeg',
    'qt' => 'video/quicktime',
    'mov' => 'video/quicktime',
    'viv' => 'video/vnd.vivo',
    'vivo' => 'video/vnd.vivo',
    'avi' => 'video/x-msvideo',
    'movie' => 'video/x-sgi-movie',
    'vts' => 'workbook/formulaone',
    'vtts' => 'workbook/formulaone',
    '3dmf' => 'x-world/x-3dmf',
    '3dm' => 'x-world/x-3dmf',
    'qd3d' => 'x-world/x-3dmf',
    'qd3' => 'x-world/x-3dmf',
    'wrl' => 'x-world/x-vrml'
  }
end